[General]
; element_list = POSITION,NORMAL,TANGENT,COLOR,TEXCOORD,BLENDWEIGHT,BLENDINDICES
element_list = POSITION,NORMAL,TANGENT,COLOR,TEXCOORD,TEXCOORD1,BLENDWEIGHT,BLENDINDICES
# 这里reverse_mod_path要注意使用的路径符号问题，路径里必须使用/而不是\，结尾必须有/
reverse_mod_path = E:/Temproary/Jahoda/
ib_category_list = Head,Body,Dress
; ib_category_list = Head,Body
vb_category_list = Position,Texcoord,Blend
mod_name = Jahoda

[Format]
; read_dxgi_format = DXGI_FORMAT_R16_UINT
read_dxgi_format = DXGI_FORMAT_R32_UINT

; write_dxgi_format = DXGI_FORMAT_R16_UINT
write_dxgi_format = DXGI_FORMAT_R32_UINT

[CategoryStride]
Position = 40
Texcoord = 20
Blend = 32

[Split]
repair_tangent = nearest

; read_ib_format = DXGI_FORMAT_R16_UINT
read_ib_format = DXGI_FORMAT_R32_UINT
; write_ib_format = DXGI_FORMAT_R16_UINT
write_ib_format = DXGI_FORMAT_R32_UINT

position_category = Position

[OutputStride]
; 打包buf时的目标stride（用于处理游戏VB含padding的情况）
; 留空则使用CategoryStride的值
Texcoord = 28
